steps:
  # Retrieve credentials from Fort Knox
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=ornitho-pubsub --format='get(payload.data)' | tr '_-' '/+' | base64 -d > pubsubkey.json" ]
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: '.'
  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'test' ]
    dir: '.'
  # Build and Deploy the analyzer and notifier service (Cloud Run Container)
  # ---------
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'Dockerfile.eventHandlers', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_EVENTHANDLERS}:$COMMIT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_EVENTHANDLERS}:$COMMIT_SHA' ]
  # Deploy  container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME_EVENTHANDLERS}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_EVENTHANDLERS}:$COMMIT_SHA'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
  # Build and Deploy the scraper
  # ---------
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'Dockerfile.scraper', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_SCRAPER}:$COMMIT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_SCRAPER}:$COMMIT_SHA' ]
  # Deploy scraper container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME_SCRAPER}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_SCRAPER}:$COMMIT_SHA'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_EVENTHANDLERS}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_SCRAPER}:$COMMIT_SHA'
